services:

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - game_server
      - number_factory
    networks:
      - mastermind

  game_server:
    build:
      context: ./game
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 3
    depends_on:
      - redis_game_state_primary
    networks:
      - mastermind

  redis_game_state_primary:
    image: redis:latest
    restart: always
    networks:
      mastermind:
        aliases:
          - redis_game_state_primary

  redis_game_state_replica:
    image: redis:latest
    command: redis-server --replicaof redis_game_state_primary 6379 
    restart: always
    networks:
      mastermind:
        aliases:
          - redis_game_state_replica

  number_factory:
    build:
      context: ./number_factory/
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 2
    depends_on:
      - redis_number_store_primary
    networks:
      - mastermind

  redis_number_store_primary:
    image: redis:latest
    restart: always
    networks:
      mastermind:
        aliases:
          - redis_number_store_primary

  redis_number_store_replica:
    image: redis:latest
    command: redis-server --replicaof redis_number_store_primary 6379
    restart: always
    networks:
      mastermind:
        aliases:
          - redis_number_store_replica

networks:
  mastermind:
    driver: bridge
