services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"  # Map instance 1 to port 8001 on the host
    environment:
      - INSTANCE=api1

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"  # Map instance 2 to port 8002 on the host
    environment:
      - INSTANCE=api2

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # The load balancer will be accessible on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
